// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PedidosApp.DAL;

namespace PedidosApp.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("PedidosApp.Models.OrdenDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenDetalle");
                });

            modelBuilder.Entity("PedidosApp.Models.Ordenes", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuplidorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdenId");

                    b.ToTable("ordenes");
                });

            modelBuilder.Entity("PedidosApp.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.Property<int>("Inventario")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoId");

                    b.ToTable("productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 450m,
                            Descripcion = "Salami",
                            Inventario = 10
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 60m,
                            Descripcion = "ListaMilk",
                            Inventario = 40
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 45m,
                            Descripcion = "Naranja sin azucar",
                            Inventario = 10
                        },
                        new
                        {
                            ProductoId = 4,
                            Costo = 60m,
                            Descripcion = "Carnation",
                            Inventario = 15
                        },
                        new
                        {
                            ProductoId = 5,
                            Costo = 45m,
                            Descripcion = "Leche Condenzada",
                            Inventario = 7
                        });
                });

            modelBuilder.Entity("PedidosApp.Models.Suplidores", b =>
                {
                    b.Property<int>("SuplidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.HasKey("SuplidorId");

                    b.ToTable("suplidores");

                    b.HasData(
                        new
                        {
                            SuplidorId = 1,
                            Nombre = "Rica"
                        },
                        new
                        {
                            SuplidorId = 2,
                            Nombre = "Induveca"
                        },
                        new
                        {
                            SuplidorId = 3,
                            Nombre = "Nestle"
                        });
                });

            modelBuilder.Entity("PedidosApp.Models.OrdenDetalle", b =>
                {
                    b.HasOne("PedidosApp.Models.Ordenes", null)
                        .WithMany("ordenDetalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PedidosApp.Models.Productos", "productos")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
